### ISSUE TITLE
Django5 not supported?

### ISSUE THREAD

**Issue by duaneking** [axnsan12/drf-yasg#878]
# Bug Report

The most modern version of Django that has been released (v5+) does not seem to be supported.

## Description

Django 5 was released and does not seem to be supported based on the contents of the README.

## Is this a regression?

Technically, yes and no. The release of a newer version of the supported product is important. As a result, this has the potential to block upgrades made to be on a version that supports security fixes..

## Minimal Reproduction

See readme.

## Stack trace / Error message

See readme.

## Your Environment

See above.

**Comment by 21adrian1996** [comment]
When using Django 5 (concretely 5.0.1), the following error appears:

```
AttributeError at /redoc/

'__proxy__' object has no attribute '_delegate_text'
```

Is this already a know issue?

**Comment by Wullink** [comment]
> When using Django 5 (concretely 5.0.1), the following error appears:
> 
> ```
> AttributeError at /redoc/
> 
> '__proxy__' object has no attribute '_delegate_text'
> ```
> 
> Is this already a know issue?

I am having the same issue

**Comment by milssky** [comment]
Currently, Redoc works correctly on Django 5.1.1.

**Comment by JoelLefkowitz** [comment]
Hey @milssky thank you for raising this. Since #902 we run our test project agains Django v5.1.x. Could you please provide some more replication steps?

**Comment by duaneking** [comment]
Why was I assigned this?

Was this fixed?

**Comment by JoelLefkowitz** [comment]
@duaneking, my bad I was meant to address this question to you: 

> Hey @milssky thank you for raising this. Since https://github.com/axnsan12/drf-yasg/pull/902 we run our test project agains Django v5.1.x. Could you please provide some more replication steps?

At present Django 5.1.x is working, I didn't want to close the issue you originally raised without first hearing back if you were still facing the bug

**Comment by duaneking** [comment]
It's still assigned to me, please remove it.  I actively don't want this assigned to me.  It is unprofessional and rude to assign things to people without their consent. I'm not being given the option to remove myself. 5.1 support doesn't matter, there are higher versions released.
