### ISSUE TITLE
swagger_fake_view  => TypeError: get_queryset() missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by Amoki** [axnsan12/drf-yasg#289]
Hi,

After update to 1.12.x, I used swagger_fake_view for all my routes.

For many routes (not all of them), I have the following trace:
```
view's type.get_parsers raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/amoki/.local/share/virtualenvs/python-api-0OvACxs8/lib/python3.7/site-packages/drf_yasg/inspectors/base.py", line 28, in call_view_method
    res = getattr(view, method_name)()
TypeError: get_queryset() missing 1 required positional argument: 'self'
```

After investigations, It comes from:
https://github.com/axnsan12/drf-yasg/blob/master/src/drf_yasg/generators.py#L492
where we try to call `get_queryset` from the class and not an instance, so we don't have the self parameter.

Therefore, I can't check self.swagger_fake_view because there is no self :/

**Comment by axnsan12** [comment]
This is fixed in 1.12.1.

**Comment by Amoki** [comment]
Oops, I forgot I tried to bisect my problems and stayed in 1.12.0...

Thanks! It fixes my everything :)
