### ISSUE TITLE
Compatibility issues with djangorestframework==3.14.0

### ISSUE THREAD

**Issue by matthew-hodgins** [axnsan12/drf-yasg#810]
# Bug Report

djangorestframework upgraded to version 3.14.0 last night. This breaks compatibility with drf-yasg 1.21.3.

## Description

With version 3.14.0, rest_framework.serializers.NullBooleanField was removed. 

## Is this a regression?

No.

## Minimal Reproduction

```code

```

## Stack trace / Error message

```code
  File "/home/.../lib/python3.6/site-packages/drf_yasg/inspectors/field.py", line 406, in <module>
    (serializers.NullBooleanField, (openapi.TYPE_BOOLEAN, None)),
AttributeError: module 'rest_framework.serializers' has no attribute 'NullBooleanField'
```

## Your Environment

```code
Python 3.6.9
Django==3.2.15
djangorestframework==3.14.0
drf-yasg==1.21.3
```

**Comment by na0495** [comment]
i did encounter the same issue with the env
```
Django==3.2.9
djangorestframework>=3.12.2
drf-yasg>=1.20.0
```

**Comment by pablodiegoss** [comment]
Same issue here, had to pin djangorestframework to 3.13.1 to work with drf-yasg 1.21.3

**Comment by JoelLefkowitz** [comment]
Thanks for flagging, Ill get a fix out for this today.
